# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '02:00'
      timezone: 'Asia/Seoul'
    groups:
      actions-patch-minor:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'npm'
    directory: '/apps/mobile'
    schedule:
      interval: 'weekly'
      time: '02:00'
      timezone: 'Asia/Seoul'
    # Expo 호환성을 위해 이 디렉토리의 핵심 의존성 업데이트를 모두 무시합니다.
    ignore:
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: '@types/react'
      - dependency-name: 'react-native'
    groups:
      mobile-production:
        dependency-type: 'production'
      mobile-development:
        dependency-type: 'development'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '02:00'
      timezone: 'Asia/Seoul'
    labels:
      - 'dependabot'
    ignore:
      - dependency-name: 'tailwindcss'
        update-types: ['version-update:semver-major']
    groups:
      web-core:
        patterns:
          - 'next'
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      storybook:
        patterns:
          - '*storybook*'
      npm-production:
        dependency-type: 'production'
        update-types:
          - 'patch'
        exclude-patterns:
          - 'next'
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      npm-development:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
