export const kindergartenRegisterContent = Object.freeze({
  headerTitle: '유치원 정보 입력',
  titleLine1: '유치원 정보를',
  titleLine2: '입력해 주세요',
  nameLabel: '유치원명',
  namePlaceholder: '유치원명을 입력해주세요',
  addressLabel: '주소',
  addressPlaceholder: '유치원 주소를 입력해주세요',
  numberLabel: '유치원 전화번호',
  numberPlaceholder: '유치원 전화번호를 입력해주세요',
  ownerNameLabel: '대표자명',
  ownerNamePlaceholder: '대표자명을 입력해주세요',
  phoneLabel: '대표 전화번호',
  phonePlaceholder: '대표 전화번호를 입력해주세요',
  nextButtonLabel: '다음',
});
