const guardianKindergartenAttendingContent = {
  checkInLabel: '등원',
  checkOutLabel: '하원',
  dayFinishedLabel: '오늘 하루를 마쳤어요',
  noticePreparingMessage: '선생님이 알림장을 준비하고 있어요',
  noticePreparingIconSrc: '/images/ico_note_writing_none.png',
  noticePreparingIconAlt: '알림장 준비 중',
  noticeArrivedMessage: '오늘의 알림장이 도착했어요',
  noticeArrivedIconSrc: '/images/ico_note_complete.png',
  noticeArrivedIconAlt: '알림장 도착',
  noticeViewLabel: '보러 가기',
  noticeConditionLabel: '컨디션',
  noticeStoolLabel: '배변',
  noticeViewAllLabel: '전체보기',
  albumTitle: '오늘의 앨범',
  albumViewAllLabel: '전체 보기',
  albumPlaceholderSrc: '/images/image_kindergarten_album_none.png',
  albumPlaceholderAlt: '앨범 사진 자리',
  albumEmptyImageSrc: '/images/img_empty_album_pre_attend.png',
  albumEmptyImageAlt: '앨범 없음',
  albumEmptyTitle: '아직 올라온 사진이 없어요',
  albumPreviousLabel: '이전 앨범 보러가기',
  albumArrivedAccent: '새로운 사진',
  albumArrivedSuffix: '이 도착했어요',
  historyLabel: '유치원 연결 이력 보기',
  noNoticeMessage: '이 날은 도착한 알림장이 없어요',
  calendarEmptyMessage: '이 날의 등원 기록이 없어요',
  pastNoticesLabel: '지난 알림장 보기',
} as const;

export { guardianKindergartenAttendingContent };
