export const ownerMypageContent = Object.freeze({
  ownerBadgeLabel: '원장',
  accountSectionTitle: '내 계정',
  releasePermissionLabel: '운영 권한 해제하기',
  withdrawBlockedModalTitleLine1: '원장 권한이 있어',
  withdrawBlockedModalTitleLine2: '바로 탈퇴할 수 없어요',
  withdrawBlockedModalDescriptionLine1: '유치원 운영 권한을 먼저 종료한 뒤',
  withdrawBlockedModalDescriptionLine2: '회원 탈퇴를 진행할 수 있어요.',
  withdrawBlockedModalConfirmLabel: '권한 해제하러 가기',
  otherInfoTitle: '기타 정보',
  logoutLabel: '로그아웃',
  withdrawLabel: '탈퇴하기',
  profilePageTitle: '프로필',
  kindergartenPageTitle: '유치원 정보',
  kindergartenOperationTabLabel: '운영',
  kindergartenPricingTabLabel: '요금',
  kindergartenBasicInfoTitle: '기본 정보',
  kindergartenNameLabel: '유치원명',
  kindergartenAddressLabel: '주소',
  kindergartenPhoneLabel: '전화번호',
  noConfirmedInfoText: '확인된 정보가 없습니다.',
  profileEditPageTitle: '프로필 수정하기',
  editInfoButtonLabel: '정보 수정하기',
  ownerNameLabel: '이름',
  ownerPhoneLabel: '연락처',
  ownerEmailLabel: '이메일',
  ownerNamePlaceholder: '이름을 입력해주세요',
  ownerPhonePlaceholder: '연락처를 입력해주세요',
  ownerEmailPlaceholder: '이메일을 입력해주세요',
  profileSaveButtonLabel: '저장하기',
});

