const STORAGE_KEYS = {
  RECENT_PLACE: 'RECENT_PLACE',
  RECENT_SEARCH_KEYWORD: 'RECENT_SEARCH_KEYWORD',

  ACCESS_TOKEN: 'ACCESS_TOKEN',

  LINKED_SOCIAL_USER: 'LINKED_SOCIAL_USER',
} as const;

const MAX_RECENT_ITEMS = 30;

export { STORAGE_KEYS, MAX_RECENT_ITEMS };
