const STORAGE_KEYS = {
  RECENTLY_VIEWED_PLACE: 'recently_viewed_place',
  RECENTLY_SEARCHED_KEYWORD: 'recently_searched_keyword',

  ACCESS_TOKEN: 'ACCESS_TOKEN',

  LINKED_SOCIAL_USER: 'LINKED_SOCIAL_USER',
} as const;

const MAX_RECENT_ITEMS = 30;

export { STORAGE_KEYS, MAX_RECENT_ITEMS };
