const STORAGE_KEYS = {
  RECENTLY_VIEWED_PLACE: 'recently_viewed_place',
  RECENTLY_SEARCHED_KEYWORD: 'recently_searched_keyword',

  ACCESS_TOKEN: 'ACCESS_TOKEN',

  USER: 'USER',
  SOCIAL_USER: 'SOCIAL_USER',
  OWNER_PROFILE: 'OWNER_PROFILE',
  MYPAGE_ROLE_VIEW: 'MYPAGE_ROLE_VIEW',
  OWNER_NOTICE_TEMPLATE_LOAD: 'OWNER_NOTICE_TEMPLATE_LOAD',
  OWNER_NOTICE_TEMPLATE_ROUNDTRIP: 'OWNER_NOTICE_TEMPLATE_ROUNDTRIP',
  OWNER_DAILY_NOTICE_DRAFT_PREFIX: 'OWNER_DAILY_NOTICE_DRAFT_',
  LINKED_SOCIAL_USER: 'LINKED_SOCIAL_USER',
  BASE_POINT_TYPE: 'BASE_POINT_TYPE',
} as const;

const MAX_RECENT_ITEMS = 30;

export { STORAGE_KEYS, MAX_RECENT_ITEMS };
