import {
  DOG_BREED_MAP,
  DOG_SERVICE_MAP,
  DOG_SAFETY_FACILITY_MAP,
  VISITOR_AMENITY_MAP,
  SERVICE_ICON_MAP,
} from '@entities/kindergarten';

const TOTAL_SERVICE_MAP = {
  ...DOG_BREED_MAP,
  ...DOG_SERVICE_MAP,
  ...DOG_SAFETY_FACILITY_MAP,
  ...VISITOR_AMENITY_MAP,
};

export { TOTAL_SERVICE_MAP, SERVICE_ICON_MAP };
