name: 'Setup Node.js and pnpm'
description: 'Setup Node.js and pnpm with cache'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'
